######################################################################
# Automatically generated by qmake (3.0) Mon Oct 17 19:33:58 2016
######################################################################

QT += testlib
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
HEADERS += sortordertest.h
SOURCES += sortordertest.cpp
